import type { Provenance } from "@/lib/types";

/**
 * Single source of truth for how data confidence is described to the user.
 *
 * Product rule: nothing renders a number without also rendering its
 * provenance. GTA 6 has not shipped; presenting an estimate as a fact would be
 * the fastest way to lose the audience this product depends on.
 */
export const PROVENANCE_META: Record<
  Provenance,
  { label: string; short: string; description: string; tone: "verified" | "community" | "estimated" | "projection" | "unverified" }
> = {
  verified: {
    label: "Verified",
    short: "VER",
    description: "Confirmed against an official Rockstar source.",
    tone: "verified",
  },
  community: {
    label: "Community data",
    short: "COM",
    description: "Reported by players and cross-checked across at least two independent sources.",
    tone: "community",
  },
  estimated: {
    label: "Estimated",
    short: "EST",
    description: "Derived by our own formulas from other data points. Treat as a working figure.",
    tone: "estimated",
  },
  "ai-projection": {
    label: "AI projection",
    short: "AI",
    description: "Generated by the model. Lowest confidence. Check it before acting on it.",
    tone: "projection",
  },
  unverified: {
    label: "Unverified",
    short: "UNV",
    description:
      "Circulating with nothing reliable behind it, or not answered yet. Do not act on this.",
    tone: "unverified",
  },
};

/** Ordered worst to best, so a set of records can be summarised by its weakest link. */
// Worst to best. `unverified` sits below `ai-projection`: a projection is at
// least the output of something, and this is the absence of one.
const RANK: Provenance[] = [
  "unverified",
  "ai-projection",
  "estimated",
  "community",
  "verified",
];

export function weakestProvenance(items: { provenance: Provenance }[]): Provenance {
  return items.reduce<Provenance>(
    (worst, item) =>
      RANK.indexOf(item.provenance) < RANK.indexOf(worst) ? item.provenance : worst,
    "verified",
  );
}
